config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jobs
  root to: 'jobs#index'
  get 'category', to: 'jobs#category', as: 'category'
  get 'contact', to: 'jobs#contact', as: 'contact'
  get 'compprofile', to: 'jobs#compprofile', as: 'compprofile'
  resources :contacts , only: [:new,:create]
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :jobs
end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :title, presence: true
    validates :description, presence: true
    validates :email, presence: true,format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

end

app/models/job.rb
class Job < ActiveRecord::Base

	validates :title, presence: true
	validates :location, presence: true
	validates :description, presence: true
	validates :comp_name, presence: true
	validates :comp_url, presence: true
	validates :email_comp, presence: true
	validates :email_customer, presence: true

	#scope for searching ==>  index page
	scope :search, -> (keyword){ where('keywords LIKE ?',"%#{keyword.downcase}%") if keyword.present?}
	scope :filter, ->(filter) {where('category_id like ?',"%#{filter}") if filter.present? }

	#filtering categories ==> index page doesnt works right now.
   # scope :filter, -> (category_id){ joins(:categories).where('categories.id=?',category_id)}

	before_save :set_keywords

	protected
	def set_keywords
		self.keywords=[title,description,comp_name].map(&:downcase).join(' ')
	end

	belongs_to :category, dependent: :destroy

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

    #controller for contact us page
    def contactus
    end

    def new
        @message=Contact.new
    end

    def create
        @message=Contact.create(message_params)
        if @message.save
            redirect_to root_path
        else
            render new_contact_path
        end
    end

    private
    def message_params
        params.require(:contact).permit(:title,:description,:email)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

	def index
		@post=Job.search(params[:keyword]).filter(params[:filter]).paginate(page: params[:page], per_page: 6)
		@category=Category.all
		@post_count=Job.search(params[:keyword]).filter(params[:filter]).count
	end


	def contact
	end

	def show
		@post=Job.find(params[:id])
	end

	def new
		@post=Job.new
	end

	def category
		@category=Category.all
	end

	def compprofile
	end

	def create
		@post=Job.create(post_params)

		if @post.save
			redirect_to jobs_path
		else
			render new_job_path
		end
	end

	private
	def post_params
		params.require(:job).permit(:title,:category_id,:location,:description,:email_customer,:comp_name,:comp_url,:email_comp)

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/contacts/new.html.erb
<div class="col-md-4 col-md-offset-2">
    <h1 class="text-center">Send us a message.</h1>
    <%= form_for(@message) do |f| %>
    <div class="field">
        <%= f.label :Message_Title %>
        <%= f.text_field :title ,class: 'form-control'%>
    </div>

    <div class="field">
        <%= f.label :Message_description %>
        <%= f.text_area :description, rows:6, cols:7,class: 'form-control' %>
    </div>

    <div class="field">
        <%= f.label :Your_email %>
        <%= f.text_field :email, class: 'form-control' %>
    </div>
    <br>

    <div class="action">
        <%= f.submit "Submit", class: 'btn btn-primary btn-block' %>
    </div>
    <br>
    <br>
    <% end  %>
    </div>

<div class="col-md-4 field_with_errors">

        <% if @message.errors.any? %>
        <div id="error_explanation">
            <p class="text-danger">

                <%= pluralize(@message.errors.count, "error") %> prohibited this post from being saved:
            </p>

            <ul>
                <% @message.errors.full_messages.each do |message| %>
                <li class="text-danger"><%= message %></li>
                <% end %>
            </ul>
        </div>
        <% end %>


</div>

app/views/jobs/category.html.erb
<div class="col-md-5 col-md-offset-2">
<h1>Job Categories</h1>
<hr>
    <% @category.each do |c| %>
    <p>

 <%= link_to(c.name.humanize) %>
    </p>
    <% end %>
</div>

app/views/jobs/compprofile.html.erb
<div class="col-md-4 col-md-offset-1">



<h1>This Feature is...</h1>
<h1>Comming soon..</h1>
</div>

app/views/jobs/contact.html.erb
<h1>Contact us</h1>

app/views/jobs/index.html.erb
<div class="col-md-12">
<div class="col-md-4 col-md-offset-2" style="padding-right:0px;">
<form>
    <input type="text" value="<%= params[:keyword]%>" name="keyword" class="col-md-6">
    <%= submit_tag "Search", class: 'btn btn-danger btn-md' ,style: "margin-left:10px;" %>

</form>
</div>
    <button class="btn btn-primary col-md-1" style="margin-left:0px;">Post a job</button>
</div>



<div class="row">

<div class="col-md-7 showjob col-md-offset-1"   >

    <p class="col-md-9 col-md-offset-3 search-p" style="color:#e99;"> Total of <%= @post_count %>  results found</p>
    <% @post.each do |job| %>



        <div class="col-md-12 jobinfo">
        <div class="col-md-9">

        <p class="text-center job-title"><%= link_to("#{ job.title.humanize}",job,class: 'job-title') %> </p>

            <p class="text-center">
                <%= job.comp_name.humanize %>,
            <%= job.created_at.strftime("%B, %d,%Y") %>

            <span class="label label-danger pull-right ">
            <%= job.category.name.humanize%>


            </span>

            </p>



</div>


            <div class="col-md-3 col-md-offset">
            <p>
            <i class="fa fa-map-marker"></i>
            <%= job.location.humanize %>,
            </p>


            <i class="fa fa-clock-o"></i>
            <%= time_ago_in_words(job.created_at)%> ago




            </div>

        </div>


        <% end %>



        </div>


<div class="col-md-3 sidebar">
    <h1>Job Categories</h1>

<div class="sidebar-content categories">
    <% @category.each do |category| %>
        <p class="text-center text-border">
        <%= link_to(category.name.humanize, jobs_path(filter: category.id) ) %>
        </p>
    <% end %>


</div>

</div>

    </div>

<div class="col-md-12">
    <div class="col-md-5 col-md-offset-3">
        <%= will_paginate @post%>
    </div>
</div>

app/views/jobs/new.html.erb
<div class="container">

	<div class="col-md-7">

		<%= form_for(@post) do |f| %>
		<h3> Step 1: Post your job</h3>
		<hr>

		<div class="field">
			<div class="col-md-3">
				<%= f.label :Job_Title %>
			</div>

			<div class="col-md-9">
				<%= f.text_field :title ,class: 'form-control',placeholder: 'eg: ruby on rails intern'%>
			</div>


			<div class="field col-md-12">
				<div class="col-md-3">
					<label>Category</label>
				</div>
				<% cities_array = Job.all.map { |city| [city.title, city.id] } %>
				<%= f.collection_select(:category_id,Category.all,:id,:name) %>

			</div>


			<div class="field col-md-12">
				<div class="col-md-3">
					<%= f.label :location %>
				</div>

				<div class="col-md-9">
					<%= f.text_field :location ,class: 'form-control' , placeholder: 'eg: Durbar marg'%>
				</div>
			</div>

			<div class="field col-md-12">
				<div class="col-md-12">
					<%= f.label :description %>
				</div>
				<div class="col-md-12">
					<%= f.text_area :description ,class: 'form-control', rows:10, cols:10 %>
				</div>
			</div>

			<div class="field col-md-12">
				<div class="col-md-3">
					<%= f.label :customer_email %>
				</div>
				<div class="col-md-9">
					<%= f.text_field :email_customer ,class: 'form-control',placeholder: 'Email where job seekers can contact you'%>
				</div>
			</div>

			<h3>Step 3: Company details</h3>
			<hr>





			<div class="field col-md-12">
				<div class="col-md-3">

					<%= f.label :company_name %>
				</div>
				<div class="col-md-9">

					<%= f.text_field :comp_name ,class: 'form-control'%>
				</div>
			</div>

			<div class="field col-md-12">
				<div class="col-md-3">
					<%= f.label :company_URL %>
				</div>

				<div class="col-md-9">
					<%= f.text_field :comp_url ,class: 'form-control',placeholder: 'www.techlab.com'%>
				</div>
			</div>

			<div class="field col-md-12">
				<div class="col-md-3">
					<%= f.label :Company_email %>
				</div>
				<div class="col-md-9">
					<%= f.text_field :email_comp ,class: 'form-control', placeholder: 'where do we contact you?'%>
				</div>
			</div>

			<br>

			<div class=" field action col-md-5 pull-right">
				<%= f.submit "Done" , class: 'btn btn-danger btn-md btn-block'%>
			</div>






			<% end %>
		</div>
	</div>
	<div class="col-md-3 field_with_errors">

		<% if @post.errors.any? %>
		<div id="error_explanation">
			<p class="text-danger">

				<%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:
			</p>

			<ul>
				<% @post.errors.full_messages.each do |message| %>
				<li class="text-danger"><%= message %></li>
				<% end %>
			</ul>
		</div>
		<% end %>
	</div>
</div>

app/views/jobs/show.html.erb
<div class="showjob col-md-6 col-md-offset-2">

<h1> <%= @post.comp_name.humanize %> </h1>
<p class="showp">

 <%= @post.location %>,
 Posted on: <%= @post.created_at.strftime("%B %d %Y") %>
</p>

 <hr>

<h1>  <%= @post.title.humanize %> </h1>
<p> Job Description: <%= simple_format(@post.description) %> </p>




<p> URL: <%= link_to nil, "http://#{@post.comp_url}", target: '_blank' %> </p>

<p> Apply at: <%= link_to("#{@post.email_customer}") %> </p>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Techjobsinnepal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<link href="//netdna.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.css" rel="stylesheet">
</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.5";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="col-md-12" style="background-color:#f6f8f8;">
  <%= image_tag("background.png",style: 'height:90px;width:120px;',class:'col-md-4 col-md-offset-1') %>

  <h1 class="col-md-4" style="margin-top:20px;"> <span class="tech-jobs">Tech jobs</span> in Nepal</h1>
</div>

<div class="col-md-12" style="margin-bottom:20px;background-color:#f6f8f8;">
	<div class="col-md-7 col-md-offset-1">



<ul class="nav nav-pills">

    <li role="presentation">  <%= link_to("Home", root_path ) %>   </li>
    <li role="presentation"><%= link_to("Post a Job", new_job_path ) %></li>
    <li role="presentation"><%= link_to("Categories", category_path) %></li>
    <li role="presentation"><%= link_to("Company Profile", compprofile_path) %></li>
    <li role="presentation"><%= link_to("Contact Us" , new_contact_path )%></li>
    <li role="presentation"><%= link_to("Sign in" , new_user_session_path )%></li>


</ul>
	</div>
</div>

<%= yield %>

<footer class="col-md-12">

<div class="col-md-4">
<p>

	&copy Copyright Tech Jobs in Nepal

</p>
</div>

<div class="col-md-4">
	<p>


      Handcrafted with <i class="fa fa-heart-o"></i> by developers from Nepal.

  </p>
</div>

<div class="col-md-4">
	<p> Contact </p>
	<p>Email: info@techjobsinnepal.com</p>
	<p>Contact: 9801134052</p>

</div>

</footer>

</body>
</html>